# Generated by Django 4.2.27 on 2026-03-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('book_id', models.IntegerField(db_index=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('purchase', 'Purchase'), ('review', 'Review')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_interactions',
            },
        ),
    ]
