# Generated by Django 4.2.27 on 2026-03-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_days', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_methods',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_index=True)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingmethod')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
    ]
